/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisSection: typeof import('./src/components/sections/AnalysisSection.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppForm: typeof import('./src/components/AppForm.vue')['default']
    AppMap: typeof import('./src/components/AppMap.vue')['default']
    CalculatorSection: typeof import('./src/components/sections/CalculatorSection.vue')['default']
    DecorSection: typeof import('./src/components/sections/DecorSection.vue')['default']
    DeliversSection: typeof import('./src/components/sections/DeliversSection.vue')['default']
    DocumentationSection: typeof import('./src/components/sections/DocumentationSection.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FounderSection: typeof import('./src/components/sections/FounderSection.vue')['default']
    GallerySection: typeof import('./src/components/sections/GallerySection.vue')['default']
    HomePage: typeof import('./src/components/pages/HomePage.vue')['default']
    IconArrowDown: typeof import('./src/components/icons/IconArrowDown.vue')['default']
    IconArrowLeft: typeof import('./src/components/icons/IconArrowLeft.vue')['default']
    IconArrowTopRight: typeof import('./src/components/icons/IconArrowTopRight.vue')['default']
    IconFolder: typeof import('./src/components/icons/iconFolder.vue')['default']
    IconLibrary: typeof import('./src/components/icons/iconLibrary.vue')['default']
    IconLogoMap: typeof import('./src/components/icons/IconLogoMap.vue')['default']
    IconMuseum: typeof import('./src/components/icons/iconMuseum.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconUnlock: typeof import('./src/components/icons/iconUnlock.vue')['default']
    InvestmentSection: typeof import('./src/components/sections/InvestmentSection.vue')['default']
    MainMenu: typeof import('./src/components/sections/main/mainMenu.vue')['default']
    MainSection: typeof import('./src/components/sections/MainSection.vue')['default']
    PerfomanceSection: typeof import('./src/components/sections/PerfomanceSection.vue')['default']
    SecureSection: typeof import('./src/components/sections/SecureSection.vue')['default']
    TestPage: typeof import('./src/components/testPage.vue')['default']
    UiButton: typeof import('./src/components/ui/uiButton.vue')['default']
    UiCircle: typeof import('./src/components/ui/uiCircle.vue')['default']
    UiSelect: typeof import('./src/components/ui/uiSelect.vue')['default']
    UiSlider: typeof import('./src/components/ui/uiSlider.vue')['default']
  }
}
